### ISSUE TITLE
Fix docker setting and setup external database

### ISSUE THREAD

**Issue by stevew1007** [stevew1007/Mission-Runner-API#6]
Currently docker configration is broken. More specificly need to fix following item
- Corret the image name and program entry point.
- Cannot use git discribe --tag in docker environment. Need to pass versioning from docker tag

In `config.py`
```Python
from pathlib import Path

def is_docker():
    cgroup = Path('/proc/self/cgroup')
    dockerenv = Path('/.dockerenv')
    return dockerenv.is_file() or cgroup.is_file() \
        and 'docker' in cgroup.read_text()

version = str()
if is_docker():
    version = os.environ.get('DOCKER_TAG')
else:
    try:
        version = subprocess.run(
            ['git describe --tags --always --dirty'],
            capture_output=True,
        ).stdout.decode('utf-8').strip()
    except Exception:
        version = 'unknown'
```
In `docker-compose.yml`
```yaml
version: '3'
services:
  mission-runner:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: "$(git describe --tags --always --dirty)"
```
In `Dockerfile`
```Dockerfile
FROM python:3.10-slim

RUN useradd mission_runner

WORKDIR /home/mission_runner

ENV FLASK_APP mission_runner.py
ENV FLASK_DEBUG 1
ARG IMAGE_TAG
ENV DOCKER_TAG=${IMAGE_TAG}

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY api api
COPY migrations migrations
COPY mission_runner.py config.py boot.sh ./
RUN chmod +x boot.sh

RUN chown -R mission_runner:mission_runner ./
USER mission_runner

EXPOSE 5000
ENTRYPOINT [ "./boot.sh" ]
```
